settings :
  debug : true
  displayErrorDetails : true;

view  :
 template_path : 'app/templates'
 twig :
    cache : 'cache/twig'
    debug : true

db  :
    driver    : 'mysql'
    host       : 'localhost'
    dbname     : 'top5'
    username   : 'root'
    password   : 'password'

application:
    doc_path : 'home'
    doc_index_file : 'index.yaml'
    img_path : '/images/places'