-- MySQL Script generated by MySQL Workbench
-- 06/12/14 00:25:42
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema top5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `top5` DEFAULT CHARACTER SET latin1 ;
USE `top5` ;

-- -----------------------------------------------------
-- Table `top5`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `top5`.`customers` ;

CREATE TABLE IF NOT EXISTS `top5`.`customers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME,
  `updated_at` DATETIME,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `top5`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `top5`.`tags` ;

CREATE TABLE IF NOT EXISTS `top5`.`tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `short` VARCHAR(25) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME,
  `updated_at` DATETIME,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `short` (`short` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `top5`.`places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `top5`.`places` ;

CREATE TABLE IF NOT EXISTS `top5`.`places` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `suburb` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(4) NOT NULL,
  `state` VARCHAR(3) NOT NULL DEFAULT 'VIC',
  `lat` DOUBLE NULL DEFAULT NULL,
  `lng` DOUBLE NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT 'TBA',
  `contact_details` VARCHAR(45) NULL DEFAULT 'TBA',
  `ratings` INT(11) NULL DEFAULT '0',
  `price_per_display` DOUBLE NULL DEFAULT '0',
  `all_clicks` INT(11) NULL DEFAULT '0',
  `clicks_after_last_bill` INT(11) NULL DEFAULT '0',
  `all_displays` INT(11) NULL DEFAULT '0',
  `displays_after_last_bill` INT(11) NULL DEFAULT '0',
  `created_at` DATETIME,
  `updated_at` DATETIME,
  `customer_id` INT(11) NOT NULL,
  `tag_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_2` (`name` ASC, `address` ASC, `postcode` ASC),
  INDEX `customer_id` (`customer_id` ASC),
  INDEX `name` (`name` ASC),
  INDEX `fk_places_tags1_idx` (`tag_id` ASC),
  CONSTRAINT `places_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `top5`.`customers` (`id`),
  CONSTRAINT `fk_places_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `top5`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
